[build]
builder = "nixpacks"
buildCommand = "npm install --only=production"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"

[build.ignore]
- "client/"
- "client/*"
- "build/"
- "dist/"
- "src/"
- "public/"
- "*.html"
- "*.css"
- "*.jsx"
- "*.tsx" 